### ISSUE TITLE
Only show the quicklinks under project metadata for owners

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#249]
I kinda wanna show the "show all properties" link for all visitors, but the other three only for owners. Would be nice if we could add e.g. a property for each actionlink in IProjectInfoProps.ts that could be used as "AudienceTargeting":"Owners","AudienceTargeting":"None" or similar.

![image](https://user-images.githubusercontent.com/1837390/27634549-ed46dcc4-5c03-11e7-9c7f-6a6700e9f54d.png)

If this is complicated, a fair solution is to only show all the quicklinks for owners.

**Comment by olemp** [comment]
Converting `ModalLink` to a full component with state in order to use state variable `shouldRender` which is initially set to false if `audienceTargeting` is not set to `none`.

In `componentDidMount` we check if the current user matches the `audienceTargeting` using a new util function `doesUserMatchAudience`.

**Comment by olemp** [comment]
I almost want to make a component `AudienceTargetedComponent` which extends `React.Component` which can be extended by the compontents which needs it.

Same procecure was used in https://github.com/Puzzlepart/prosjektportalen/issues/248
