### ISSUE TITLE
"Prosjektets faser" in Norwegian

### ISSUE THREAD

**Issue by oleber123** [Puzzlepart/prosjektportalen#415]
Category

[ ] Enhancement

[ ] Bug

[X] Question

Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

Summary

Is it possible to get "Prosjektets faser" in Norwegian in the next version? Everything else is in Norwegian. 
I think the text is in the script "pp.main.js". We can edit the script, but expect the text to be overwritten in the next version if it is not changed by you.
![image](https://user-images.githubusercontent.com/25792850/31540853-17869986-b00d-11e7-9921-60e6ebe4f30b.png)

2.1.8 Version

**Comment by tarjeieo** [comment]
Hi,

This happens only because you've installed this to an environment where english is the default language of the term store. If you delete the "Project portal" term sets and term group, change the default language to norwegian, and install again you will get better labels. Note that it's also possible to delete the term group and then install just the taxonomy-1044.pnp package again. This will only install the norwegian terms.

NB: If you install the Project portal to the same site collection again you might want to use -SkipData and -SkipDefaultConfig parameters to avoid duplicate data and config elements (see https://github.com/Puzzlepart/prosjektportalen/wiki/Installation). 

Good luck!
