### ISSUE TITLE
Error in search refiner after restore of Site Collection

### ISSUE THREAD

**Issue by PrinsMild** [Puzzlepart/prosjektportalen#416]
#### Category

[X] Bug

#### Environment

[X] SharePoint 2016

#### Summary

When taking a restore after backup of the Site Collection, the Search Refiners are empty. The result is a frontpage listing absolute all the content from all lists. And so the loading of the Frontpage is taking several minutes. This happends also if the search index is reset.

#### Version

Please specify what version you are using: [2,0 and up to 2,.1.3 ]

#### Expected / Desired Behavior / Question
The web part should be a CSWP so it is easier to make adjustments.
Also the Display Template "Glitterind_Item_Project" should be made visible in the library. Now it's hidden and cannot be used in a CSWP.

#### Observed Behavior
The Frontpage should only list a summary of the sub sites (Projects)

#### Steps to Reproduce
Take a backup of PP Site Collection and Restore it to another in the same farm.

**Comment by tarjeieo** [comment]
Hi,

Search configuration is persisted in the search service, not in the site collection, and connected to the site collection in a way. That's why when backing up a site collection you need to export search config for the site collection as well, and use this in the restore process.

We don't use display templates anymore, the files are not included in later releases. 

To fix the issue, you need to either export/import search configuration from the old site collection, or install the search config again, using e.g. apply-pnpprovisioningtemplate -path root.pnp -handlers Search
