### ISSUE TITLE
WebPart "Latest Projects" causes login prompt in certain SharePoint 2013 environments

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#430]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[x] SharePoint 2013

[ ] SharePoint 2016

**Comment by tarjeieo** [comment]
Both /_api/web/webs and /_api/web/webinfos forces a login prompt for non-admin users in SP2013. 

Using `/_api/web/webs/?$select=title,ServerRelativeUrl,Created,effectivebasepermissions&$filter=(effectivebasepermissions/high%20gt%2032)` works for SP2013, but doesn't work for SPO - haven't tested SP2016. 

@olemp any idea about the complexity of introducing environment execution logic? I don't really want to introduce this complexity since we've been able to get this far without this complexity, but I'm not sure...

**Comment by olemp** [comment]
We can use JSOM here.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.1.18
