### ISSUE TITLE
Excel-export: Format date-values as date in Excel cells

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#531]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

The output of date-fields in the Excel-sheet is formatted as text, with a long datestring, e.g. '2017-07-27T07:38:53.0000000Z'. This string is not easily converted to dateformat in Excel. 

A suggested solution is to set the format for the cell to date. We have the field's "displaymode" which contains "DateTime" as a setting. Based on this, it should be possible to set dateformat for the cell: https://www.npmjs.com/package/xlsx#data-types. We might also have to render the datefield as shortdate-string for it to be accepted (e.g. 2017-07-27). 

NB: Beware timezones - Convert to user's timezone before formatting the date.

**Comment by tarjeieo** [comment]
See also https://github.com/SheetJS/js-xlsx/issues/126

**Comment by Remi749** [comment]
I was unable to create a converter for the date-fields in the Excel-sheet. I think a possible solution for this is to create a type and add this to the data.columns (at a specific column) and set it to the correct excel format in the exportToExcel function. I was unable to figure this out and it's probably harder to implement than what it was first thought out to be. Installing the SheetJS turned out unsuccesfull. @olemp should probably take a quick look and see if he can implement this later. Closed until further notice.
