### ISSUE TITLE
Portfolio - horizontal scrollbar hides columns when content is wider than screen

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#692]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [ 2.5.14]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Summary

![image](https://user-images.githubusercontent.com/1837390/63516745-e03e8e00-c4ed-11e9-9cb9-8f07c4730c5c.png)

**Comment by olemp** [comment]
Please specify what version you are using!

**Comment by olemp** [comment]
Might take a look at https://github.com/OfficeDev/office-ui-fabric-react/issues/6611 @tarjeieo @damsleth. Maybe we should use just some CSS instead of `Sticky` and `ScrollablePane`.

**Comment by olemp** [comment]
Any progress @damsleth?

**Comment by tarjeieo** [comment]
Scrolling bonanza with the UI fabric of 2.5.14. Anything we can do to improve this? Status @damsleth ?

![image](https://user-images.githubusercontent.com/1837390/66401246-25a61480-e9e3-11e9-8a83-
590cffaa80d3.png)

**Comment by damsleth** [comment]
This seems to be related to #650 and #685 .

Looking at the DynamicPortfolio tsx and the UI , it seems the topmost scrollbar really doesn't serve a purpose, since it only scrolls the headers and not the whole portfolio view.
The bottom scrollbar is sufficient IMO.
![pp692](https://user-images.githubusercontent.com/7300548/66650791-be31d400-ec31-11e9-9b5d-ad3d941f211c.gif)

As a quick fix, I'd suggest hiding the horizontal scrollbar when we add the scroll EventListener inside componentDidMound, like in the StickyHeader scss-file that was introduced in #686 and later removed.

`        let stickyAbove = document.querySelector("[class*='stickyAbove-']");
        if (stickyAbove != null) {
            stickyAbove.addEventListener("scroll", this.handleStickyScroll);
            stickyAbove.style.overflowX="hidden";
        }`

PS: I'm not getting an outer right scrollbar in the environment i'm testing, since it seems everything from #s4-workspace down to the scrollablePane scales vertically, thus not rendering a scrollbar.

PPS: the portfolio scrollablePane requires a window height of 860px for the bottom scrollbar to be visible - is this an acceptable minimum height?

**Comment by olemp** [comment]
In https://github.com/Puzzlepart/prosjektportalen365/blob/master/SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx I added 90% height to the outmost div and then 100% to the container containing the ScrollablePane. It would be better to look at the same approach as MS are using in their list views using flex box so that the scrollablepane uses all available space vertically.

**Comment by tarjeieo** [comment]
Tested now in pzlcloud! Excellent work @damsleth ! Thanks!

**Comment by tarjeieo** [comment]
Still an issue it seems. The vertical scrollbar is hidden underneath the main page scrollbar - weird behavior. Isn't there a way to make the content go 100% height and let the main scroll bar control the scrolling? (What @olemp said above).

**Comment by tarjeieo** [comment]
Maybe fixed!?
